var vocab = [
'a slew of/a lot of',
'abhor/嚴惡',
'abominable/可惡',
'about face/大轉軚',
'above the fray/避免衝突',
'abridge/curtail',
'acolyte/助手 追隨者',
'acrimony/尖刻 n',
'adrift/without purpose or guidance',
'afoot/in progress',
'agonising/焦慮',
'all is not lost/尚有一絲希望',
'aloof/冷漠',
'affront/侮辱',
'animus/仇視 惡意',
'annex/吞併',
'armrest/扶手',
'assiduous/刻苦',
'assuage/緩解',
'at liberty/不受監禁',
'avant-garde/前衛',
'backbencher/普通議員',
'ballyhooed/被大吹大擂',
'banish/驅走',
'bask in/沐浴在',
'batten down the hatches/做好應對危機準備',
'This material may be protected by copyright.',
'batty/insane 古怪',
'bear,bore him out/為他作證',
'bear the brunt of/首當其衝',
'beat about the bush/說話轉彎抹角',
'beauty is in the eye of the beholder/情人眼裏出西施',
'befuddled/感糊塗',
'beguiled/受騙',
'belligerent/好鬥的',
'bellwether/領頭羊',
'beseech/懇求',
'bespoke/adj 訂製',
'bestowed/授予',
'bigwig/大亨',
'bilious/惡心 難看',
'blab/泄密 v',
'blithely/漫不經心地',
'bluster/靠嚇',
'boffin/科研工作者',
'boggle/吃驚',
'boorishly/粗魯地',
'bootleg/非法銷售',
'brace for/prepare for',
'brazen/厚顏無恥',
'bromide/老調 unoriginal remark',
'burgeoning/激增',
'bury the hatchet/言歸於好',
'calumny/誹謗',
'canvass/拉票',
'caricature/誇張描述',
'capricious/任性',
'catch-22/進退兩難、左右兩難',
'cauterize the wound/ 燒肉止血',
'certitude/確信',
'chancy/冒險的',
'chameleon/變色龍',
'chide/斥責',
'chill-out zone/relaxed area',
'chip in/貢獻（在合作的事上）',
'chore/煩人的事',
'churlish/rude',
'churn out/粗制濫造',
'chutzpah/厚臉皮 肆無忌憚',
'clandestine/秘密的',
'clique/a small group',
'clout/勢力',
'cock-a-hoop/洋洋得意',
'cognoscenti/行家',
'collegiality/共同承擔責任',
'come full circle/兒圈回到原地',
'come to terms/和解 屈服',
'come what may/no matter what happens',
'commandeer/征用',
'compactly/緊湊地',
'compunction/內疚',
'concoct/編制（指數） 調制',
'consummate/完成（交易）',
'copious/abundant',
'copiously/大量地',
'cosseting/過度保護',
'counteract/對抗 抗衡',
'coup/政變 巧妙之舉',
'crackpot/不切實際 古怪的',
'crash out/逃出',
'cuddly/和藹可親的',
'cul-de-sac/死胡同',
'cushy/輕鬆 舒適',
'deleterious/有害',
'demur/遲疑',
'despot/專制君主',
'devil-may-care/逍遙自在的',
'diktats/強制法令',
'din/嘈雜聲',
'disaffection/不滿',
'disillusionment/幻想破滅',
'disparage/詆毀',
'disrepair/失修',
'dissimulate/掩飾',
'do his bidding/follow his order request',
'doddle/輕而易舉的事',
'dolt/笨蛋',
'doting/adj 溺愛',
'dressed to the nines/打扮得絕頂漂亮',
'dubious/可疑',
'dust off/重新採用',
'enamor/迷戀',
'engrossed/全神貫注',
'ensnare/誘捕',
'enter the fray/介入鬥爭',
'epiphany/頓悟',
'equivocate/模梭兩可',
'excoriation/狠批',
'exculpatory/無辜的',
'exoneration/免除責任',
'face down/overcome sb sth with determination',
'fail-safe/萬無一失',
'fall upon/猛烈攻擊',
'fanfare/大鑼大鼓',
'fawning/阿諛奉承',
'fazed/慌張',
'fealty/（對領主）忠誠',
'fetish/迷戀物',
'figurine/手板公仔',
'flesh out/充實 e.g. speech',
'foment/挑起',
'flat-footed/笨手笨腳的',
'flesh out/充實；支持（證據）',
'flout/公然藐視',
'forshadow/預示',
'fray/爭鬥',
'freewheeling/隨心所欲的',
'furore/公憤',
'gawp/v 盯著（電話）',
'give short shrift/讖悔',
'give sb the slip/避 甩開某人',
'give the lie to/證明…不真實',
'glean/obtain',
'gory/沾滿血污',
'go to the dogs/墮落；沒落',
'gobsmacked/大吃一驚',
'goings-on/勾當',
'goof/愚蠢錯誤',
'grandee/大人物',
'granular/粒狀',
'ground out/',
'grubby/肮髒',
'gull/欺騙',
'hail as/稱頌 譽為',
'hamstrung by/因而 變得無能為力',
'hand-in-glove/勾結',
'hard-charging/夾硬來',
'have skin in the game/利益悠關',
'Heaven knows/天曉得',
'heist/搶劫',
'hit and miss/欠考慮的，隨意的',
'hog/攫取 獨佔',
'hog the limelight/搶盡風頭',
'hold water/站得住腳',
'home in on/focus on, move towards',
'hyperbole/誇談',
'iconoclastic/反傳統的',
'unimpeachable/無懈可擊',
'iffy/不確定',
'ignominious/不光彩的',
'imperious/傲慢',
'impersonate/假扮',
'incorrigible/屢教不改',
'indiscriminate/盲目的',
'inferno/熊熊烈火 混亂場面',
'ingrained/根深蒂固',
'inimical/不利',
'innocuously/無害的',
'in one fell swoop/all in one go 一下子',
'in so doing',
'insinuates/暗示',
'insipid/枯燥無味的',
'interminable/無休止',
'in one"s dotage/年邁 衰老',
'in the offing/即將發生',
'intractable/stubborn',
'invariably/總是',
'jibe/嘲弄',
'joint/公共場所',
'juggernaut/不可抗拒的力量',
'knockoff/imitation',
'largesse/捐贈',
'lesser/較差 次要',
'let on/說出秘密',
'lewd/淫穢的',
'lo and behold/你瞧',
'look askance at/態度懷疑',
'look the part/似模似樣',
'look-see/一瞥',
'make head or tail of it',
'made off/逃離',
'makeshift/臨時 湊成',
'measure up to/符合…要求',
'mend the rift/修補撕裂',
'mom-and-pop/夫妻的',
'momentous/重要',
'moniker/外號',
'monotonous/單調 乏味',
'morose/陰鬱的',
'nadir/最低點',
'neophyte/新手',
'nondescript/無明顯特徵的',
'nothing is what it seems/',
'nous/智力 常識',
'nuisance/麻煩事',
'obscure/鮮為人知的 conceal',
'oblivious to/不察覺',
'oft-cited/ often cited',
'omniscient/無所不知',
'on a shoestring /tight budget',
'on the fly/in progress',
'on the mantle/衣砵',
'overreach/過份',
'out-and-out/徹頭徹尾的',
'outgrowth/outcome',
'out of whack/紊亂，out of order',
'own up to/承認',
'palpably/obviously 具體',
'panhandle/beg',
'parochial/狹隘',
'passé/過時',
'patently/obviously',
'pedigree/家譜 出身 血統',
'penury/貧困',
'pep up/使活躍',
'pernicious/惡性的',
'perverse/任性 capricious',
'pipe dream/幻想 空想',
'piqued/生氣 賭氣',
'pit against/競爭、鬥智',
'pomp/大場面',
'poon-poon/v 嗤之以鼻',
'portend/預示',
'parlous/危險 難對付的',
'precarious/不安穩的',
'precocious/早熟',
'predilection/偏愛',
'proclaim/announce officially',
'profligate/任意揮霍',
'prolific/多產的',
'prowess/本領',
'psephologist/選舉統計學家',
'pull alongside/（車）開過來',
'quintessential/典型的',
'Rabble-rousers/蠱惑人心者',
'rack up/accumulate',
'ramification/後果',
'rarefied/離地，脫離群眾',
'ratchet up/小幅提升',
'rattled/cause to feel nervous',
'Regaining your composure/恢復鎮靜',
'rein in/ keep under control',
'reminisce/緬懷',
'rhapsodise/熱情洋溢地談論',
'restive/躁動不安，難駕馭',
'retinue/隨從',
'rifle through/快速翻查',
'rile/惹惱',
'ringleader/犯罪大佬',
'root for it/為...加油',
'rote/死記硬背',
'rubicon/n. point of no return',
'rub off on him/傳給某人',
'ruffle feathers/惹怒某人',
'rumble/幫派開片；沒完沒了地進行',
'ruse/詭計',
'salient/顯著 重要',
'sassy/倜皮',
'scoff/嘲笑',
'scourge/禍源',
'scrupulous/按良心做事的',
'scupper/搞挎',
'sedative/鎮定劑',
'seemingly/表面上',
'see off/趕走',
'seethe at/怒火中燒',
'seminal/開創性',
'serviceman/軍人',
'set store by/重視',
'shoot-out/槍戰',
'shudder/顫抖',
'sinecure/休差',
'skate over/輕輕帶過',
'slapdash/馬虎',
'slick/精明',
'slowly but surely/漸有所成',
'slur/詆毀',
'smart v./感到痛苦',
'snuff out/扼殺',
'sophistry/詭辯術',
'snag/障礙 困難',
'softie/心腸軟的人',
'splurge/揮霍',
'spot on/精準',
'squabbling/爭吵',
'squalid/極骯髒',
'staggeringly/難以置信地',
'stalk/v.追蹤',
'standoffish/冷淡的',
'sterile/乏想像力',
'stupendous/驚人的',
'straight and narrow/走正路',
'streak/性格特徵',
'stricture/指責',
'swansong/最後作品',
'sycophancy/阿諛奉承',
'taken aback/大吃一驚',
'tail off/逐漸減少 弱',
'tantalize/逗引',
'tantamount/無異於',
'taunt/奚落',
'tellingly/有力（論據）',
'telltale/ revealing',
'testy/暴躁的',
'there but for the grace/無再衰啲已叫好彩',
'there is no love lost between two persons/兩人之間沒有好感',
'thoroughfare/大道',
'tied sb in knots/使困惑，使糊塗',
'tinker/修修補補',
'to fret/苦惱',
'to pass muster/及格',
'tongue-in-cheek/挖苦地',
'top brass/高軍階 有權者',
'touchy/易怒',
'touchy-feely/矯情',
'towering/exceptionally important',
'trounce/徹底打敗',
'treat it with kid gloves/應付得心慈手軟',
'trickster/騙子',
'trying/令人厭煩',
'unbecoming/態度行為不合適',
'uncharacteristically/非尋常地',
'unconscionable/過份',
'uncosted/未反映全面成本',
'unflinchingly/不畏縮地',
'unsavoury/討厭的',
'unseemly/不得體',
'unsettling/令人不安',
'unwieldly/笨重的',
'up the creek/落入困境',
'uptight/精神緊張的',
'usher/迎賓員',
'usher in/迎接',
'usurp/篡奪',
'vaunted/被吹噓的',
'veracity/真實',
'vibe/氛圍',
'visceral/',
'vitriolic/尖刻的（評論）',
'volte-face/轉軚',
'wager/打賭',
'wearisome/乏味',
'weigh in/發表有份量意見',
'well-heeled/富有的',
'well-honed/磨利了的',
'well-to-do/富裕的',
'whack/Br. share',
'whacky/古怪',
'whatnot/諸如此類的東西',
'wisecracking/說悄皮話',
'wonkish/只專注細節',
'woolly/不清晰，含糊',
'wreak havoc/造成嚴重破壞',
'wrong-footed/措手不及',
'yearn/渴望'
];